# Generated by Django 5.1.3 on 2024-11-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_genre_movie_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=None),
        ),
    ]
