# Generated by Django 5.1.3 on 2024-11-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
