# Generated by Django 5.1.3 on 2024-11-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_screen_theatre_seat_number_alter_seat_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
