# Generated by Django 5.1.3 on 2024-11-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seat_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('seat_count', models.PositiveIntegerField()),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.screen')),
            ],
        ),
    ]
