# Generated by Django 5.1.3 on 2024-11-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booked_at',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_seats',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='screening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.screening'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
    ]
