# Generated by Django 5.1.3 on 2025-01-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenProxy',
            fields=[
            ],
            options={
                'ordering': ['-total_seats'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.screen',),
        ),
    ]
