# Generated by Django 5.1.3 on 2025-01-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_screenproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenproxy',
            options={'ordering': ['-theatre']},
        ),
    ]
