# Generated by Django 5.1.3 on 2025-01-15 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_screenproxy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedBooking',
            fields=[
                ('booking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.booking')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            bases=('core.booking',),
        ),
    ]
