name: Django CI

on:
  push:
    branches: [ "feature", "develop", "main" ]
  pull_request:
    branches: [ "main", "develop", "feature" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

  merge-to-main:
    if: github.ref == 'refs/heads/feature'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout feature branch
      uses: actions/checkout@v4
      with:
        ref: feature

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Merge develop into develop
      run: |
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git fetch origin
        git checkout develop
        git merge feature
        git push origin develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}